doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  connections:
    default:
      server: '%env(resolve:DATABASE_URL)%'
      options: {}
  types:
    user_id: BirthdayReminder\Infrastructure\Persistence\Doctrine\Type\UserId
  document_managers:
    default:
      auto_mapping: true
      mappings:
        BirthdayReminder:
          is_bundle: false
          type: attribute
          dir: '%kernel.project_dir%/src/Domain'
          prefix: 'BirthdayReminder\Domain'

when@prod:
  doctrine_mongodb:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false
    document_managers:
      default:
        metadata_cache_driver:
          type: service
          id: doctrine_mongodb.system_cache_pool

  framework:
    cache:
      pools:
        doctrine_mongodb.system_cache_pool:
          adapter: cache.system
