version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./:/var/www:cached
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    tty: true