version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./:/var/www:cached
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    tty: true

  mysql:
    ports:
      - '3306:3306'
    restart: always
    image: mysql:8.0
    volumes:
      - vkbd-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

volumes:
    vkbd-data:
