version: '3.9'

services:
  app:
    image: ${APP_IMAGE:-birthday-reminder/app-prod}:${APP_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "80:8080"
    environment: &app-env
      - APP_ENV=prod
      - APP_DEBUG=false
      - APP_SECRET
      - VK_API_URL
      - VK_API_TIMEOUT
      - VK_API_VERSION
      - VK_API_ACCESS_TOKEN
      - VK_API_CONFIRMATION_KEY
      - DATABASE_URL

  cron:
    image: ${CRON_IMAGE:-birthday-reminder/cron}:${APP_IMAGE_TAG:-latest}
    init: true
    depends_on:
      - app
    environment: *app-env

  mongo:
    image: mongo:6.0.2
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mongodata:
