version: '3.9'

services:
  php:
    image: vkbd/php-dev:${PROJECT_VERSION:-latest}
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
