<?php

declare(strict_types=1);

namespace Tests\Constraint\Promise;

use PHPUnit\Framework\Constraint\Constraint;

final class PromiseResolvesWith extends Constraint
{
    /** @var mixed */
    private $value;

    /**
     * @param mixed $value
     */
    public function __construct($value)
    {
        $this->value = $value;
    }

    protected function matches($other): bool
    {
        return parent::matches($other); // TODO: Change the autogenerated stub
    }

    protected function failureDescription($other): string
    {
        return 'promise resolves with value';
    }

    public function toString(): string
    {
        return "resolves with {$this->value}";
    }
}
