name: Deploy

on: [ workflow_dispatch ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Copy docker-compose.prod.yml to remote host
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 1m
          source: docker-compose.prod.yml
          target: /app
          overwrite: true

      - name: Deploy to remote host
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app
            docker login --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} ${{ secrets.CONTAINER_REGISTRY }}
            APP_IMAGE=${{ secrets.CONTAINER_REGISTRY }}/birthday-reminder/app-prod docker-compose -f docker-compose.prod.yml pull app
             APP_IMAGE=${{ secrets.CONTAINER_REGISTRY }}/birthday-reminder/app-prod docker-compose -f docker-compose.prod.yml up -d \
              -e "APP_SECRET=${{ secrets.APP_SECRET }}" \
              -e "VK_API_URL=${{ secrets.VK_API_URL }}" \
              -e "VK_API_TIMEOUT=2" \
              -e "VK_API_VERSION=${{ secrets.VK_API_VERSION }}" \
              -e "VK_API_ACCESS_TOKEN=${{ secrets.VK_API_ACCESS_TOKEN }}" \
              -e "VK_API_CONFIRMATION_KEY=${{ secrets.VK_API_CONFIRMATION_KEY }}" \
              -e "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
              -e "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" \
              -e "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}"
            docker logout ${{ secrets.CONTAINER_REGISTRY }}
