name: PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        php-versions: ['7.4', '8.0']
        include:
          - php-version: '8.0'
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mysqli, pdo_mysql, pcntl
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-bust-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-bust-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Run PHP CS Fixer
        run: bin/php-cs-fixer-ci.sh

      - name: Run PHP Code Sniffer
        run: composer phpcs

      - name: Run test suite
        run: composer phpunit

      - name: Run infection
        run: composer infection

      - name: Run psalm
        run: composer psalm-ci
