name: PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mysqli, pdo_mysql, pcntl
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-bust-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-bust-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Run PHP CS Fixer
        run: |
          chmod +x ./bin/php-cs-fixer-ci.sh
          ./bin/php-cs-fixer-ci.sh

      - name: Run test suite
        run: composer phpunit

      - name: Run infection
        run: composer infection
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: Run psalm
        run: composer psalm-ci
